"""empty message

Revision ID: e6b70ef50c6b
Revises: c556ca1b6b7a
Create Date: 2020-03-23 03:02:05.659688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6b70ef50c6b'
down_revision = 'c556ca1b6b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('association', 'actor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
